<?php

namespace AppBundle\Repository;

/**
 * ApartadoSalaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApartadoSalaRepository extends \Doctrine\ORM\EntityRepository
{
}
