<?php

namespace AppBundle\Repository;

/**
 * SalaPersonasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalaPersonasRepository extends \Doctrine\ORM\EntityRepository
{
}
