<?php

namespace AppBundle\Repository;
	
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    /*public static function userSession(UserRepository $repository)
    {
    	$user = $this->container->get('security.token_storage')->getToken()->getUser();
        //$username = $user->getUsername();
        $id_user = $user->getId();
        var_dump($id_user);
        return $repository->createQueryBuilder('c')
            ->where("c.id = :id_user")
            ->setParameter('id_user', $id_user);
    }*/
    public static function getUsers(SalaPersonasRepository $repository)
    {
        return $repository->createQueryBuilder('c')
            ->where("c.idPersona = 1")
            ->orderBy('c.idPersona');
    }
}